SELECT SUM(A.VAL * B.VAL) AS DOT  FROM A,B 
WHERE A.J=1 AND B.J=2 AND A.I=B.I

SELECT A.I, B.J ,SUM(A.VAL * B.VAL) AS RESULT
FROM A
INNER JOIN B 
ON A.J = B.I
GROUP BY A.I,B.J;

SELECT A.I, B.J ,SUM(A.VAL* B.VAL)
FROM A,B
WHERE A.J=B.I
GROUP BY A.I,B.J;

SELECT B,D  FROM STREETS WHERE A='AUEB' AND D<10 
GROUP BY B,D
HAVING COUNT(DISTINCT ID)<=3;

SELECT DISTINCT ID,DIRECTION FROM STREETS
WHERE A<>B;

SELECT DISTINCT ID AS ROAD,A,B,D,DIRECTION FROM STREETS  --COMMENT
WHERE A != 'AUEB' AND B !='AUEB' AND A<>B 
AND ID IN (       --F DIRECTION
  SELECT DISTINCT ID FROM STREETS WHERE DIRECTION='F' OR DIRECTION='R'
  GROUP BY ID
  HAVING SUM(D)<=15 AND COUNT(DISTINCT ID)<=3)
;
